spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# SEON Security Configuration
seon.admin.username=${SEON_ADMIN_USERNAME:admin}
seon.admin.password=${SEON_ADMIN_PASSWORD:admin}

# SEON Paths Configuration
seon.astah.filepath=${SEON_ASTAH_FILEPATH:astah_seon.asta}
seon.astah.script=${SEON_ASTAH_SCRIPT:jars/astah-command.sh}
seon.images.output=${SEON_IMAGES_OUTPUT:src/main/resources/static/images}